export { B2B_FRESH_START } from './data/rows';
export { fetchB2BData, fetchInboundOwnerTotals, fetchClients, fetchInboundBoard, fetchKamOrders, fetchOutreachLeads } from './data/reads';
export type { B2BData } from './data/reads';
export { B2B_STATS_BRANCH, fetchB2BPipelineStats, istToday } from './stats/pipeline';
export type { B2BPipelineStats } from './stats/pipeline';
export { fetchB2BBulk } from './orders/history';
export type { ClientOrderHistory } from './orders/history';
export { lookupEnqId } from './leads/enq-lookup';
export type { EnqLookup } from './leads/enq-lookup';
export { fetchInboundKamLoad, fetchKamLoad, fetchVerticalStats } from './leads/kam-load';
export type { VerticalStats } from './leads/kam-load';
export { ENQ_RESOLVE_CAP, kamEnquiryIdsToResolve, clientMetricsFrom, fetchClientOrderRows, firstOrderValueFromAggregates, invalidateClientTickets, orderDatesFromAggregates, resolveKamOrders } from './orders/details';
export type { ClientOrderDetails, ClientOrderRow } from './orders/details';
export { clientFromSeed, planClientSeed } from './leads/client-seed';
export type { ClientSeedPlan } from './leads/client-seed';
export { deleteB2BRow, upsertClient, upsertInboundLead, upsertKamOrder, upsertOutreachLead } from './data/writes';
export { fetchTargets, saveTargets } from './stats/targets';
export { fetchUnifiedLeads } from './leads/unified';
export type { LeadSource, UnifiedLead, UnifiedStatus } from './leads/unified';
