export { B2B_FRESH_START } from './b2b/rows';
export { fetchB2BData, fetchClients, fetchInboundBoard, fetchKamOrders, fetchOutreachLeads } from './b2b/reads';
export type { B2BData, InboundBoardPage } from './b2b/reads';
export { B2B_BRANCH, fetchB2BPipelineStats, istToday } from './b2b/pipelineStats';
export type { B2BPipelineStats } from './b2b/pipelineStats';
export { fetchClientOrderHistories, normalizeClientPhone } from './b2b/orderHistory';
export type { ClientOrderHistory } from './b2b/orderHistory';
export { lookupEnqId } from './b2b/enqLookup';
export type { EnqLookup } from './b2b/enqLookup';
export { B2B_VERTICALS, fetchInboundKamLoad, fetchKamLoad, fetchVerticalStats } from './b2b/kamLoad';
export type { VerticalRep, VerticalStats } from './b2b/kamLoad';
export { ENQ_RESOLVE_CAP, ORDER_DETAIL_PHONE_CAP, clientMetricsFrom, fetchClientOrderRows, firstOrderValue, invalidateClientTickets, orderDatesFromRows, resolveKamOrders } from './b2b/orderDetails';
export type { ClientOrderDetails, ClientOrderRow, KamOrderResolution, KamOrderResolveResult } from './b2b/orderDetails';
export { clientFromSeed, planClientSeed } from './b2b/clientSeed';
export type { ClientSeedCandidate, ClientSeedPlan } from './b2b/clientSeed';
export { deleteB2BRow, upsertClient, upsertInboundLead, upsertKamOrder, upsertOutreachLead } from './b2b/writes';
export { fetchTargets, saveTargets } from './b2b/targets';
export { fetchUnifiedLeads } from './b2b/unifiedLeads';
export type { LeadSource, UnifiedLead, UnifiedLeadsResult, UnifiedStatus } from './b2b/unifiedLeads';
