/**
 * Mock data used when KYLAS_API_KEY is not configured.
 * Replace with real API calls once credentials are set up in .env.local
 */

import type { Lead, Ticket, DashboardStats } from "./types";

export const mockLeads: Lead[] = [
  {
    id: 1,
    name: "Priya Sharma",
    email: "priya.sharma@techcorp.in",
    phone: "+91 98765 43210",
    company: "TechCorp India",
    status: "New",
    source: "Website",
    assignedTo: "Ravi Kumar",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    value: 150000,
  },
  {
    id: 2,
    name: "Arun Patel",
    email: "arun.patel@solutions.io",
    phone: "+91 91234 56789",
    company: "Solutions IO",
    status: "Contacted",
    source: "Referral",
    assignedTo: "Meera Singh",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    value: 80000,
  },
  {
    id: 3,
    name: "Sneha Reddy",
    email: "sneha.reddy@fintech.co",
    phone: "+91 99887 65432",
    company: "FinTech Co",
    status: "Qualified",
    source: "LinkedIn",
    assignedTo: "Ravi Kumar",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
    value: 320000,
  },
  {
    id: 4,
    name: "Vikram Nair",
    email: "vikram.nair@startupx.com",
    phone: "+91 98001 23456",
    company: "StartupX",
    status: "Proposal Sent",
    source: "Cold Call",
    assignedTo: "Anita Desai",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date().toISOString(),
    value: 220000,
  },
  {
    id: 5,
    name: "Deepa Krishnan",
    email: "deepa@globalmart.in",
    phone: "+91 70000 11223",
    company: "GlobalMart",
    status: "Won",
    source: "Email Campaign",
    assignedTo: "Meera Singh",
    createdAt: new Date(Date.now() - 345600000).toISOString(),
    updatedAt: new Date().toISOString(),
    value: 500000,
  },
  {
    id: 6,
    name: "Rohit Mehta",
    email: "rohit.mehta@cloudbiz.net",
    phone: "+91 88888 77766",
    company: "CloudBiz",
    status: "Lost",
    source: "Trade Show",
    assignedTo: "Anita Desai",
    createdAt: new Date(Date.now() - 432000000).toISOString(),
    updatedAt: new Date().toISOString(),
    value: 90000,
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 101,
    subject: "Unable to access account dashboard",
    contactName: "Priya Sharma",
    contactEmail: "priya.sharma@techcorp.in",
    status: "Open",
    priority: "High",
    assignedTo: "Support Team",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 86400000).toISOString(),
  },
  {
    id: 102,
    subject: "Invoice not received for last month",
    contactName: "Arun Patel",
    contactEmail: "arun.patel@solutions.io",
    status: "In Progress",
    priority: "Medium",
    assignedTo: "Billing Team",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 172800000).toISOString(),
  },
  {
    id: 103,
    subject: "Feature request: Export to CSV",
    contactName: "Sneha Reddy",
    contactEmail: "sneha.reddy@fintech.co",
    status: "Pending",
    priority: "Low",
    assignedTo: "Product Team",
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
    dueDate: null,
  },
  {
    id: 104,
    subject: "API integration not working",
    contactName: "Vikram Nair",
    contactEmail: "vikram.nair@startupx.com",
    status: "Open",
    priority: "Urgent",
    assignedTo: "Tech Support",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
    dueDate: new Date(Date.now() + 43200000).toISOString(),
  },
  {
    id: 105,
    subject: "Password reset not working",
    contactName: "Deepa Krishnan",
    contactEmail: "deepa@globalmart.in",
    status: "Resolved",
    priority: "High",
    assignedTo: "Support Team",
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    dueDate: null,
  },
];

export const mockDashboardStats: DashboardStats = {
  leads: {
    total: mockLeads.length,
    newToday: 1,
    won: mockLeads.filter((l) => l.status === "Won").length,
    lost: mockLeads.filter((l) => l.status === "Lost").length,
    conversionRate: Math.round(
      (mockLeads.filter((l) => l.status === "Won").length / mockLeads.length) * 100
    ),
  },
  tickets: {
    total: mockTickets.length,
    open: mockTickets.filter((t) => t.status === "Open").length,
    inProgress: mockTickets.filter((t) => t.status === "In Progress").length,
    resolved: mockTickets.filter((t) => t.status === "Resolved").length,
    avgResolutionHours: 18,
  },
};
